// Which spots are inland water rather than open coast.
//
// The marine API has no concept of a riverbank: asked for waves at Payangadi
// Puzha it snaps to the nearest OCEAN grid cell — 4.7 km out — and returns the
// swell there. Measured: Payangadi Puzha 1.32 m / 9.95 s from a point 4.7 km
// offshore, Chembalikundu 1.10 m / 9.75 s from 4.0 km offshore. Those are real
// numbers for the open sea and meaningless on a river, so the wave rows are
// hidden for these places rather than shown as if they applied.
//
// Tides are NOT hidden: Kerala's backwaters and river mouths are genuinely
// tidal, so the tide table remains the useful part of the card there.
//
// Kept here rather than in tidedata.json because that file is regenerated by
// the scraper, which would drop the flag on every refresh.
const INLAND = new Set([
  'Payangadi Puzha',   // "puzha" is Malayalam for river
  'Chembalikundu',
])

export function isInland(label) {
  return INLAND.has(String(label || '').trim())
}
